### ISSUE TITLE
Trouble making django-fluent-pages work in Ubuntu production server with gevent

### ISSUE THREAD

**Issue by chongeva** [django-fluent/django-fluent-pages#127]
Good morning, everyone. I am having trouble getting django-fluent-pages to work in my Ubuntu production server, running on Gunicorn with gevent. The problem seems to have something to do with gevent importing the apps at the same frame with django-fluent-pages.
It works 100% fine in my localhost.
I don't know what am I missing, or how to solve this. I really want to use django-fluent-pages for my project, but I can't move forward if it doesn't work in production server.

Does anyone have any idea how to get it to work without clashing with gevent? Or know what's the real cause?

This is the error message I get whenever I load a page.

ImportError at /

No module named page_type_plugins
Exception Value: No module named page_type_plugins
Exception Location: /var/www/tc_two/local/lib/python2.7/site-packages/gevent/builtins.py in __import__, line 93

````
Internal Server Error: /
Traceback (most recent call last):
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 270, in resolve
    for pattern in self.url_patterns:
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/proj/tc_two/tc_two/urls.py", line 76, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 267, in urls
    return self.get_urls(), 'admin', self.name
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 251, in get_urls
    url(r'^%s/%s/' % (model._meta.app_label, model._meta.model_name), include(model_admin.urls)),
  File "/var/www/tc_two/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 564, in urls
    return self.get_urls()
  File "/var/www/tc_two/local/lib/python2.7/site-packages/parler/admin.py", line 321, in get_urls
    urlpatterns = super(TranslatableAdmin, self).get_urls()
  File "/var/www/tc_two/local/lib/python2.7/site-packages/polymorphic_tree/admin/parentadmin.py", line 153, in get_urls
    base_urls = super(PolymorphicMPTTParentModelAdmin, self).get_urls()
  File "/var/www/tc_two/local/lib/python2.7/site-packages/polymorphic/admin/parentadmin.py", line 283, in get_urls
    self._lazy_setup()
  File "/var/www/tc_two/local/lib/python2.7/site-packages/polymorphic/admin/parentadmin.py", line 89, in _lazy_setup
    child_models = self.get_child_models()
  File "/var/www/tc_two/local/lib/python2.7/site-packages/fluent_pages/adminui/urlnodeparentadmin.py", line 64, in get_child_models
    for plugin in page_type_pool.get_plugins():
  File "/var/www/tc_two/local/lib/python2.7/site-packages/fluent_pages/extensions/pagetypepool.py", line 85, in get_plugins
    self._import_plugins()
  File "/var/www/tc_two/local/lib/python2.7/site-packages/fluent_pages/extensions/pagetypepool.py", line 198, in _import_plugins
    import_apps_submodule("page_type_plugins")
  File "/var/www/tc_two/local/lib/python2.7/site-packages/fluent_utils/load.py", line 55, in import_apps_submodule
    print _import_module('{0}.{1}'.format(app, submodule))
  File "/var/www/tc_two/local/lib/python2.7/site-packages/fluent_utils/load.py", line 69, in _import_module
    print __import__(module_label, fromlist=classnames)
  File "/var/www/tc_two/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named page_type_plugins
````

**Comment by vdboor** [comment]
It looks like gevent is overriding the way that `import` works. It adds an extra stack element, causing our import code in `fluent_utils.load.import_apps_submodule` to fail. This code tries to make sure that import errors are raised when they happen at a deeper level. This likely needs an extra exception for gevent.

**Comment by chongeva** [comment]
Currently, I don't have a separate project for debugging this. I worked my way around using eventlet instead of gevent as the worker type for Gunicorn. If eventlet works fine for all the functions I need, I'll stick to that first for my project. 

I'll try and set up a demo project that replicates this issue, and see if it can be resolved.

Thanks for replying on this issue!

**Comment by vdboor** [comment]
I've uploaded a django-fluent-utils 1.4.1 release that should fix this issue!
