### ISSUE TITLE
MultiValueDictKeyError at /admin/redirectnode/redirectnode/add/

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#130]
Happens every-time I click on "save and add another" for existing page

```python+traceback
Traceback (most recent call last):
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1506, in changeform_view
    return self.render_change_form(request, context, add=add, change=not add, obj=obj, form_url=form_url)
  File "/Users/bashu/Projects/django-fluent-pages/fluent_pages/adminui/pageadmin.py", line 102, in render_change_form
    'ct_id': int(ContentType.objects.get_for_model(obj).pk if change else request.GET['ct_id'])  # HACK for polymorphic admin
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'ct_id'"
```

Installed libraries:

django==1.10.8
django-fluent-contents==1.2.2
django-fluent-utils==1.4.1
django-mptt==0.9.0
django-parler==1.9.1
django-polymorphic==1.3
django-polymorphic-tree==1.4.2

**Comment by bashu** [comment]
@vdboor just downgraded to django-fluent-pages==1.1.2 and and django-polymorphic==1.2 and it works (except #132)
