### ISSUE TITLE
Internal CMS error: failed to fetch layout data!

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#131]
Running `example` project and trying to add a page (fluentpage page type)

```python+traceback
Traceback (most recent call last):
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/polymorphic/admin/parentadmin.py", line 225, in change_view
    real_admin = self._get_real_admin(object_id)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/polymorphic/admin/parentadmin.py", line 165, in _get_real_admin
    .values('polymorphic_ctype').get(pk=object_id)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/query.py", line 376, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/polymorphic/query.py", line 158, in _filter_or_exclude
    return super(PolymorphicQuerySet, self)._filter_or_exclude(negate, *(list(q_objects) + additional_args), **kwargs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1187, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1083, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/lookups.py", line 19, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/lookups.py", line 59, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/bashu/.virtualenvs/django-fluent-pages/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 946, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'get_layout/1'
```

**Comment by vdboor** [comment]
Thanks, I noticed the same thing! Fixed with 9d4a5cba3a265c286da9aa481f99e69daaf2bec0
